version: "3"
services:
  manager:
    volumes: 
      - '.:/Users/dylan/Documents/College/CSY5/ScalableComputing/Cyclometric/Manager/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "1000:80"