version: "3"
services:
  worker1:
    volumes: 
      - '.:/Users/dylan/Documents/College/CSY5/ScalableComputing/Cyclometric/Worker/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
  worker2:
    volumes: 
      - '.:/Users/dylan/Documents/College/CSY5/ScalableComputing/Cyclometric/Worker/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    